### ISSUE TITLE
Mobile Response Issue | RemixJS

### ISSUE THREAD

**Issue by samocodes** [bogdanpetru/react-masonry#48] opened 2023-11-11 16:58 UTC
I'm using `react-masonry` with remixjs. 
When I changed screen responsive to mobile. It starts giving me errors

`TypeError: null has no properties`
`The above error occurred in the <ft> component:`

![image](https://github.com/bogdanpetru/react-masonry/assets/127683737/2aea0e03-596d-42bf-9c6a-524364270311)

----

Versions:
Remix: `v2.1.0`
Bun: `v1.0.11`

**Comment by devtim123** [comment] 2023-11-23 15:31
I facing the same problem here.

Version:
NextJS: 13.5.2
NodeJS: v16.19.0
react-masonry: 1.0.7

What i also can mention is, that you can force error by zoom the brwoser to e.g. 150% and than resize the window often.

The is the error:
<img width="610" alt="Bildschirm­foto 2023-11-23 um 16 31 33" src="https://github.com/bogdanpetru/react-masonry/assets/6614670/e38a6325-7d17-4ffe-9804-1406d325799d">

**Comment by bogdanpetru** [comment] 2023-12-22 15:14
I will take a look, thanks for reporting. BTW merge requests are appreciated :).

**Comment by bogdanpetru** [comment] 2023-12-23 20:22
Can you provide a codesandbox or a github repo where the bug can be reproduced? Thanks!

@devtim123 @samocodes I've attempted to reproduce it, but without success. I've tested it using the example on the [homepage](https://react-masonry.bogdanpetru.eu/), trying both suggested approaches.

Could you please share a codesandbox or a GitHub repo where the bug can be reproduced? Thanks!

**Comment by NazmusSayad** [comment] 2023-12-23 22:48
Similar kind of issue with me

![image](https://github.com/bogdanpetru/react-masonry/assets/87106526/8a508f10-213e-430b-83bb-0aadb34c1180)

**Comment by bogdanpetru** [comment] 2024-04-09 16:04
Closing this until I get some reproducible examples.

**Closed by bogdanpetru** 2024-04-09 16:04 UTC

**Comment by lainNao** [comment] 2024-07-11 19:20
Hello, @bogdanpetru 
I hit the same error as this comment.
https://github.com/bogdanpetru/react-masonry/issues/48#issuecomment-1868383474

And I have created a code-sandbox link that can be reproduced.
https://w58g2p-3000.csb.app/
When I open it with chrome on android, there is currently a 100% chance of error :`TypeError: Cannot read properties of null (reading 'left')`.

**Comment by lainNao** [comment] 2024-07-19 18:04
Since a reproducible example has been provided, could you please reopen this issue?

**Comment by audeck** [comment] 2024-10-14 12:53
@bogdanpetru [Here](https://codesandbox.io/p/sandbox/3z42mg) is a minimal codesandbox of what I presume to be this same issue, only using `react-resizable-panels` and `react-masonry` (`n is null` happens immediately after dragging the resizable panel handle).

The logic is basically trying to figure out the correct `colCount` with a max column width of `260` in this case. The error happens when `colCount` falls down to `1` (and `colWidth` is therefore `100%`). You can adjust the `260` value to a lower one and everything works well until, once again, `colCount` gets to `1`.

**Comment by audeck** [comment] 2024-10-15 12:53
> The error happens when colCount falls down to 1 (and colWidth is therefore 100%).

Namely, this is because the `doesBoxFit` function returns false for all `availableSpots` if the masonry's width is lower than the item width. For my purposes, I can just constrain the resizable panel's `minSize` to accomodate at least one column, but this is obviously a workaround rather than a solution.

Not entirely familiar with the repository yet, might make PR to address the issue in the future (as the correct behavior in these cases should be to just do add a new, single column row and let the item overflow).

On a side note; non-variable item width masonry components are possible to do with just css nowadays, but what about variable item width ones? If these are possible, it'd be better to just link to at least one such solution in the README, probably.

**Comment by reesmcivor** [comment] 2024-11-05 10:52
I'm also having an issue with: 
`Uncaught TypeError: Cannot read properties of null (reading 'left')`

This causes the error: 
`<Masonry>
    <div style={{ width: "33.3%", height: '200px', backgroundColor: 'red' }}>
        Cell one
    </div>

    <div style={{ width: "33.3%", height: '200px', backgroundColor: 'blue' }}>
        Cell one
    </div>

    <div style={{ width: "33.3%", height: '300px', backgroundColor: 'yellow' }}>
        Cell one
    </div>

    <div style={{ width: "66.6%", height: '300px', backgroundColor: 'yellow' }}>
        Cell one
    </div>
</Masonry>`
